/*
  Warnings:

  - You are about to drop the column `diagnosis` on the `ClinicalHistory` table. All the data in the column will be lost.
  - You are about to drop the column `observations` on the `ClinicalHistory` table. All the data in the column will be lost.
  - You are about to drop the column `treatment` on the `ClinicalHistory` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "ClinicalHistory" DROP COLUMN "diagnosis",
DROP COLUMN "observations",
DROP COLUMN "treatment",
ADD COLUMN     "antecedentes" TEXT,
ADD COLUMN     "av_od_ph" TEXT,
ADD COLUMN     "av_od_vl" TEXT,
ADD COLUMN     "av_od_vp" TEXT,
ADD COLUMN     "av_oi_ph" TEXT,
ADD COLUMN     "av_oi_vl" TEXT,
ADD COLUMN     "av_oi_vp" TEXT,
ADD COLUMN     "diagnostico" TEXT,
ADD COLUMN     "disposicion" TEXT,
ADD COLUMN     "dp" TEXT,
ADD COLUMN     "ker_od" TEXT,
ADD COLUMN     "ker_oi" TEXT,
ADD COLUMN     "lens_od_add" TEXT,
ADD COLUMN     "lens_od_cil" TEXT,
ADD COLUMN     "lens_od_eje" TEXT,
ADD COLUMN     "lens_od_esf" TEXT,
ADD COLUMN     "lens_od_vl" TEXT,
ADD COLUMN     "lens_od_vp" TEXT,
ADD COLUMN     "lens_oi_add" TEXT,
ADD COLUMN     "lens_oi_cil" TEXT,
ADD COLUMN     "lens_oi_eje" TEXT,
ADD COLUMN     "lens_oi_esf" TEXT,
ADD COLUMN     "lens_oi_vl" TEXT,
ADD COLUMN     "lens_oi_vp" TEXT,
ADD COLUMN     "motivoConsulta" TEXT,
ADD COLUMN     "motor_vl" TEXT,
ADD COLUMN     "motor_vp" TEXT,
ADD COLUMN     "refr_od_cil" TEXT,
ADD COLUMN     "refr_od_eje" TEXT,
ADD COLUMN     "refr_od_esf" TEXT,
ADD COLUMN     "refr_oi_cil" TEXT,
ADD COLUMN     "refr_oi_eje" TEXT,
ADD COLUMN     "refr_oi_esf" TEXT,
ADD COLUMN     "rx_od_add" TEXT,
ADD COLUMN     "rx_od_cil" TEXT,
ADD COLUMN     "rx_od_eje" TEXT,
ADD COLUMN     "rx_od_esf" TEXT,
ADD COLUMN     "rx_od_vl" TEXT,
ADD COLUMN     "rx_od_vp" TEXT,
ADD COLUMN     "rx_oi_add" TEXT,
ADD COLUMN     "rx_oi_cil" TEXT,
ADD COLUMN     "rx_oi_eje" TEXT,
ADD COLUMN     "rx_oi_esf" TEXT,
ADD COLUMN     "rx_oi_vl" TEXT,
ADD COLUMN     "rx_oi_vp" TEXT,
ADD COLUMN     "sp_od" TEXT,
ADD COLUMN     "sp_oi" TEXT,
ADD COLUMN     "visitDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
